[package]
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"
name = "client"
version = "0.1.0"

[dependencies]
futures = "0.1.29"
hex = "0.3.1"
jrpc = "0.4.0"
node-template-runtime = { path = "../runtime" }
parity-scale-codec = "1.0.0"
rand = "0.7.2"
serde = "1"
serde_json = "1"
websocket = "0.23.0"

[dependencies.srml-metadata]
git = "https://github.com/paritytech/substrate.git"
rev = "870b976bec729aaf26cc237df9fd764b8f7b9d7e"
