[package]
name = "runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
parity-codec = { version = "4.1.1", default-features = false, features = ["derive"] }

[dependencies.srml-aura]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.srml-balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.substrate-client]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.substrate-consensus-aura-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.srml-executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.srml-indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.substrate-offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.substrate-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.sr-std]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.sr-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.sr-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.srml-sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.srml-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.srml-system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.srml-timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[dependencies.sr-version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'afa583011eed3e8d49ee823257a3b448a24e213b'

[build-dependencies]
substrate-wasm-builder-runner = "1.0.2"

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-executive/std",
	"srml-aura/std",
	"srml-indices/std",
	"substrate-primitives/std",
	"sr-primitives/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-sudo/std",
	"sr-version/std",
	"serde",
	"safe-mix/std",
	"substrate-consensus-aura-primitives/std",
	"substrate-offchain-primitives/std",
]
no_std = []
