name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - using: 'docker'
      image: './docker/builder/Dockerfile'
    # - run: cargo test --all
