name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://docknetwork/docknetwork-substrate-builder:tagname
      with:
        entrypoint: /bin/bash -c
        args: |
          set -uexo pipefail
          cargo test --all
