name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - run: cargo +nightly install --git https://github.com/alexcrichton/wasm-gc
    - uses: actions/checkout@v1
    - run: cargo test --all
