name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://docknetwork/docknetwork-substrate-builder:latest
      run: |
        set -uexo pipefail
        cargo test --all
